---
# tasks file
#----------------------------------------------------------------------------------
# proxy <==========================================================================
#----------------------------------------------------------------------------------
- name: Echo Proxy configuration
  debug: var=proxy
  tags:
    - proxy

- name: Setting Proxy configuration
  lineinfile:
    path: /etc/profile
    backup: no
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - { regexp: '^.*http_proxy=.*$', line: 'export http_proxy={{proxy}}' }
    - { regexp: '^.*https_proxy=.*$', line: 'export https_proxy={{proxy}}' }
    - { regexp: '^.*ftp_proxy=.*$', line: 'export ftp_proxy={{proxy}}' }
    - { regexp: '^.*rsync_proxy=.*$', line: 'export rsync_proxy={{proxy}}' }
    - { regexp: '^.*no_proxy=.*$', line: 'export no_proxy="localhost,127.0.0.1,localaddress,.localdomain,.intranet"' }
  when: proxy|default(None) != None
  tags:
    - proxy

- name: Deteting Proxy configuration
  lineinfile:
    path: /etc/profile
    backup: no
    regexp: "{{item.regexp}}"
    state: absent
  with_items:
    - { regexp: '^.*http_proxy=.*$' }
    - { regexp: '^.*https_proxy=.*$'}
    - { regexp: '^.*ftp_proxy=.*$' }
    - { regexp: '^.*rsync_proxy=.*$' }
    - { regexp: '^.*no_proxy=.*$' }
  when: proxy|default(None) == None
  tags:
    - proxy

- name: Setting current proxy
  shell: "{{item}}"
  ignore_errors: True
  args:
    warn: no
  with_items:
    - "export http_proxy={{ lookup('env', 'http_proxy') }}"
    - "export https_proxy={{ lookup('env', 'https_proxy') }}"
    - "export ftp_proxy={{ lookup('env', 'ftp_proxy') }}"
  when: proxy|default(None) != None
  tags:
    - proxy