- name: Copying configuration
  copy:
    src: files/etc/
    dest: /etc/
    owner: root
    group: root
    mode: 0664
  tags:
  - install
  - update

- name: Setting scripts permissions
  shell: "chmod 777 /etc/admin/*.sh"
  ignore_errors: True
  args:
    warn: no
  tags:
  - install
  - update

- name: Retrieving hostname
  shell: "hostnamectl hostname"
  register: current_hostname
  ignore_errors: False
  args:
    chdir: /tmp
    warn: no
  tags:
  - install

- name: Display current hostname
  debug:
    var: current_hostname
  tags:
  - install

- name: Display new hostname
  debug:
    var: new_hostname
  tags:
  - install

- name: Set a hostname
  hostname:
    name: "{{new_hostname}}"
  when: new_hostname != None and new_hostname != "" and current_hostname.stdout != new_hostname
  tags:
  - install

- name: Reboot the server
  shell: "sleep 4 && reboot"
  async: 1
  poll: 0
  when: new_hostname != None and new_hostname != "" and current_hostname.stdout != new_hostname
  tags:
  - install

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 10
    sleep: 5
    delay: 5
    timeout: 300
  when: new_hostname != None and new_hostname != "" and current_hostname.stdout != new_hostname
  tags:
  - install

- name: Updating packages
  shell: apt-get update -y && apt-get upgrade -y
  when: ansible_distribution == 'Debian'
  ignore_errors: True
  args:
    warn: no
  notify: cleaning_packages_metadata
  tags:
  - install

- name: Removing packages
  package: name={{item}} state=absent
  when: ansible_distribution == 'Debian'
  with_items:
  - alsa-topology-conf
  - alsa-ucm-conf
  - aspell
  - bluetooth
  - ispell
  - vim
  - wireless-regdb
  - wireless-tools
  - wpasupplicant
  tags:
  - install

- name: Removing packages
  package: name={{item}} state=absent
  when: ansible_distribution == 'Debian' and not secured
  with_items:
  - apparmor-utils
  - fail2ban
  - sshguard
  - ufw
  tags:
  - install

- name: Auto removing packages
  shell: apt auto-remove -y
  when: ansible_distribution == 'Debian'
  tags:
  - install

- name: Installing packages
  package: name={{item}} state=present
  when: ansible_distribution == 'Debian'
  with_items:
  - bash-completion
  - bash
  - bzip2
  - ca-certificates
  - cloud-init
  - coreutils
  - cpio
  - cron
  - curl
  - debianutils
  - e2fsprogs
  - fdisk
  - file
  - findutils
  - gpg-agent
  - gpg-wks-client
  - gpg-wks-server
  - gpg
  - gpgconf
  - gpgsm
  - gpgv
  - grep
  - gzip
  - hostname
  - iperf3
  - iproute2
  - iputils-ping
  - less
  - logrotate
  - logtail
  - mailutils-common
  - mailutils
  - mc
  - ncurses-base
  - ncurses-bin
  - net-tools
  - nfs-common
  - ntp
  - openssh-client
  - openssh-server
  - openssh-sftp-server
  - openssl
  - psmisc
  - rsync
  - screen
  - sed
  - software-properties-common
  - sshpass
  - sudo
  - tar
  - tree
  - util-linux-extra
  - util-linux-locales
  - unzip
  - vim-common
  - vim-runtime
  - vim-tiny
  - wget
  - whois
  notify: cleaning_packages_metadata
  tags:
  - install

- name: Installing packages
  package: name={{item}} state=present
  when: ansible_distribution == 'Debian' and secured
  with_items:
  - apparmor-utils
  - fail2ban
  - sshguard
  - ufw
  notify: cleaning_packages_metadata
  tags:
  - install

- name: Installing cockpit repository
  shell: '. /etc/os-release && echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main">/etc/apt/sources.list.d/backports.list'
  ignore_errors: False
  register: results
  args:
    chdir: /tmp
    warn: no
  tags:
  - install

- name: Display output
  debug:
    var: results
  tags:
  - install

- name: Installing cockpit repository
  shell: 'curl -sSL https://repo.45drives.com/setup|bash'
  ignore_errors: True
  register: results
  args:
    chdir: /tmp
    warn: no
  tags:
  - install

- name: Display output
  debug:
    var: results
  tags:
  - install

- name: Updating repositories
  shell: apt-get update -y
  when: ansible_distribution == 'Debian'
  ignore_errors: True
  args:
    warn: no
  notify: cleaning_packages_metadata
  tags:
  - install

- name: Installing packages
  package: name={{item}} state=present
  when: ansible_distribution == 'Debian'
  with_items:
  - cockpit
  - cockpit-file-sharing
  - cockpit-identities
  - cockpit-navigator
  - cockpit-sosreport
  notify: cleaning_packages_metadata
  tags:
  - install
