---
# tasks file
#----------------------------------------------------------------------------------
# cron <===========================================================================
#----------------------------------------------------------------------------------
- name: Copying cron tasks
  copy:
    src: files/etc/cron.d
    dest: /etc/
    owner: root
    group: root
    mode: 0664
  tags:
    - cron

- name: Copying monthly cron tasks
  copy:
    src: files/etc/cron.monthly
    dest: /etc/
    owner: root
    group: root
    mode: 0664
  tags:
    - cron

- name: Copying weekly cron tasks
  copy:
    src: files/etc/cron.weekly
    dest: /etc/
    owner: root
    group: root
    mode: 0664
  tags:
    - cron

- name: Copying daily cron tasks
  copy:
    src: files/etc/cron.daily
    dest: /etc/
    owner: root
    group: root
    mode: 0664
  tags:
    - cron

- name: Copying hourly cron tasks
  copy:
    src: files/etc/cron.hourly
    dest: /etc/
    owner: root
    group: root
    mode: 0664
  tags:
    - cron

- name: Updating permissions on cron directories
  shell: chmod -R 775 /etc/{{item}}
  args:
    warn: no
  with_items:
    - cron.monthly
    - cron.weekly
    - cron.daily
    - cron.hourly
  tags:
    - cron

- name: Enabling and restart services
  systemd: enabled=yes state=restarted daemon_reload=yes name={{item}}
  with_items:
    - cron    
  tags:
    - cron