---
# tasks file
#----------------------------------------------------------------------------------
# logrotate <======================================================================
#----------------------------------------------------------------------------------
- name: Setting logrotate
  replace:
    path: /etc/logrotate.conf
    regexp: "{{item.regexp}}"
    replace: "{{item.replace}}"
    backup: no
  with_items:
    - { regexp: '^(\s*)rotate\s*.*$', replace: '\1rotate {{logrotate_rotate}}' }
    - { regexp: '^(\s*)maxage\s*.*$', replace: '\1maxage {{logrotate_maxage}}' }
    - { regexp: '^(\s*)size\s*.*$', replace: '\1size {{logrotate_size}}' }
  tags:
    - logrotate

- name: Setting logrotate
  lineinfile:
    path: /etc/logrotate.conf
    backup: no
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - { regexp: '^rotate\s*.*$', line: 'rotate {{logrotate_rotate}}' }
    - { regexp: '^maxage\s*.*$', line: 'maxage {{logrotate_maxage}}' }
    - { regexp: '^size\s*.*$', line: 'size {{logrotate_size}}' }
    - { regexp: '^compress$', line: 'compress' }
  tags:
    - logrotate

- name: Find files inside logrotate.d directory
  find:
    paths: "/etc/logrotate.d/"
    patterns: "*"
  register: logrotate_files

- name: Replace rotate values
  replace:
    path: "{{item.path}}"
    regexp: '^(\s*)rotate\s*.*$'
    replace: '\1rotate {{logrotate_rotate}}'
  with_items: "{{logrotate_files.files}}"

- name: Replace maxage values
  replace:
    path: "{{item.path}}"
    regexp: '^(\s*)maxage\s*.*$'
    replace: '\1maxage {{logrotate_maxage}}'
  with_items: "{{logrotate_files.files}}"

- name: Replace size values
  replace:
    path: "{{item.path}}"
    regexp: '^size\s*.*$'
    replace: 'size {{logrotate_size}}'
  with_items: "{{logrotate_files.files}}"