- name: Copying configuration
  copy:
    src: files/etc/
    dest: /etc/
    owner: root
    group: root
    mode: 0664
  tags:
  - install

- name: Setting scripts permissions
  shell: "chmod 777 /etc/admin/*.sh"
  ignore_errors: True
  args:
    warn: no
  tags:
  - install

- name: Copying ups scheduling script
  shell: "cp /etc/nut/upssched-cmd /bin/upssched-cmd"
  ignore_errors: False
  args:
    warn: no
  tags:
  - install
  - update

- name: Setting ups permissions
  shell: "chown -R root:nut /etc/nut && chmod -R u+rwX,g+rwX /etc/nut"
  ignore_errors: False
  args:
    warn: no
  tags:
  - install
  - update

- name: Setting permissions on ups scheduling script
  file:
    path: /bin/upssched-cmd
    owner: root
    group: nut
    mode: '0770'
  tags:
  - install
  - update

- name: Allowing nut on ups devices
  shell: "touch /etc/udev/rules.d/90-nut-ups.rules"
  ignore_errors: False
  args:
    warn: no
  tags:
  - install
  - update

- name: Allowing nut on ups devices
  lineinfile:
    dest: /etc/udev/rules.d/90-nut-ups.rules
    state: present
    line: 'ACTION=="add", SUBSYSTEM=="usb", ATTR{idVendor}=="0463", ATTR{idProduct}=="ffff", MODE="0660", GROUP="nut"'
  tags:
  - install
  - update

- name: Denying ups devices for usb passthrough
  lineinfile:
    dest: /etc/xensource/usb-policy.conf
    state: present
    line: 'DENY:vid=0463 pid=ffff # MGE UPS Systems UPS'
  tags:
  - install
  - update

- name: Creating symbolic link for ups
  file:
    src: "/usr/lib/tmpfiles.d/nut-run.conf"
    dest: "/etc/tmpfiles.d/nut-run.conf"
    state: link
  tags:
  - install

- name: Creating symbolic link for xe-custom-startup.sh
  file:
    src: "/etc/admin/xe-custom-startup.sh"
    dest: "/etc/rc.d/init.d/xe-custom-startup.sh"
    state: link
  tags:
  - install

- name: Creating symbolic link for xe-custom-shutdown.sh
  file:
    src: "/etc/admin/xe-custom-shutdown.sh"
    dest: "/etc/rc.d/init.d/xe-custom-shutdown.sh"
    state: link
  tags:
  - install

- name: Creating rc.d symbolic link for xe-custom-startup.sh
  file:
    src: "/etc/rc.d/init.d/xe-custom-startup.sh"
    dest: "{{item}}"
    state: link
  with_items:
  - "/etc/rc.d/rc1.d/S99xe-custom-startup.sh"
  - "/etc/rc.d/rc2.d/S99xe-custom-startup.sh"
  - "/etc/rc.d/rc3.d/S99xe-custom-startup.sh"
  - "/etc/rc.d/rc4.d/S99xe-custom-startup.sh"
  - "/etc/rc.d/rc5.d/S99xe-custom-startup.sh"
  tags:
  - install

- name: Creating rc.d symbolic link for xe-custom-shutdown.sh
  file:
    src: "/etc/rc.d/init.d/xe-custom-shutdown.sh"
    dest: "{{item}}"
    state: link
  with_items:
  - "/etc/rc.d/rc0.d/K01xe-custom-shutdown.sh"
  - "/etc/rc.d/rc1.d/K01xe-custom-shutdown.sh"
  - "/etc/rc.d/rc2.d/K01xe-custom-shutdown.sh"
  - "/etc/rc.d/rc3.d/K01xe-custom-shutdown.sh"
  - "/etc/rc.d/rc4.d/K01xe-custom-shutdown.sh"
  - "/etc/rc.d/rc5.d/K01xe-custom-shutdown.sh"
  - "/etc/rc.d/rc6.d/K01xe-custom-shutdown.sh"
  tags:
  - install

- name: Creating /volume1 directory
  ansible.builtin.file:
    path: /volume1
    state: directory
    owner: root
    group: root
    mode: 0777
  tags:
  - install

- name: Creating /volume2 directory
  ansible.builtin.file:
    path: /volume2
    state: directory
    owner: root
    group: root
    mode: 0777
  tags:
  - install

- name: Ensuring fstab uses /volume1
  mount:
    name: "/volume1"
    src: "/dev/sdb1"
    fstype: "ext4"
    opts: "rw,nosuid,nodev,noatime"
    state: present
  tags:
  - install

- name: Ensuring fstab uses /volume2
  mount:
    name: "/volume2"
    src: "/dev/sde1"
    fstype: "ext4"
    opts: "rw,nosuid,nodev,noatime"
    state: present
  tags:
  - install
