---
# tasks file
#----------------------------------------------------------------------------------
# kubernetes <=====================================================================
#----------------------------------------------------------------------------------
- name: Updating packages
  shell: apt-get update -y && apt-get upgrade -y
  when: ansible_distribution == 'Debian'
  args:
    warn: no
  notify: cleaning_packages_metadata
  tags:
    - kubernetes

- name: Installing packages needed by Kubernetes 
  package: name={{item}} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
  notify: cleaning_packages_metadata
  when: ansible_distribution == 'Debian'
  tags:
    - kubernetes

- name: Downloading the Google Cloud public signing key
  shell: "curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg"
  tags:
    - kubernetes

- name: "Add Kubernetes repository"
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  when: ansible_distribution == 'Debian'
  tags:
    - kubernetes

- name: Updating index
  shell: apt-get update -y
  when: ansible_distribution == 'Debian'
  args:
    warn: no
  notify: cleaning_packages_metadata
  tags:
    - kubernetes

- name: Installing packages needed by Kubernetes 
  package: name={{item}} state=present
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  notify: cleaning_packages_metadata
  when: ansible_distribution == 'Debian'
  tags:
    - kubernetes

- name: Locking packages
  shell: apt-mark hold kubelet kubeadm kubectl
  when: ansible_distribution == 'Debian'
  ignore_errors: True
  args:
    warn: no
  tags:
    - kubernetes