---
# tasks file
#----------------------------------------------------------------------------------
# repositories and packages for <==================================================
#----------------------------------------------------------------------------------
- name: Add buster security APT repository
  apt_repository:
    repo: deb http://security.debian.org/debian-security/ buster/updates main contrib
    state: present
  when: ansible_distribution == 'Debian'
  tags:
    - docker

- name: Add buster security src APT repository
  apt_repository:
    repo: deb-src http://security.debian.org/debian-security/ buster/updates main contrib
    state: present
  when: ansible_distribution == 'Debian'
  tags:
    - docker

- name: Add buster APT repository
  apt_repository:
    repo: deb http://deb.debian.org/debian/ buster main contrib
    state: present
  when: ansible_distribution == 'Debian'
  tags:
    - docker

- name: Add buster updates APT repository
  apt_repository:
    repo: deb http://deb.debian.org/debian/ buster-updates main contrib
    state: present
  when: ansible_distribution == 'Debian'
  tags:
    - docker

- name: Add buster src APT repository
  apt_repository:
    repo: deb-src http://deb.debian.org/debian/ buster-updates main contrib
    state: present
  when: ansible_distribution == 'Debian'
  tags:
    - docker

- name: Updating packages
  shell: apt-get update -y && apt-get upgrade -y
  when: ansible_distribution == 'Debian'
  ignore_errors: True
  args:
    warn: no
  notify: cleaning_packages_metadata
  tags:
    - docker

#----------------------------------------------------------------------------------
# docker <==========================================================================
#----------------------------------------------------------------------------------
- name: Installing packages
  package: name={{item}} state=present
  when: ansible_distribution == 'Debian'
  with_items: 
    - curl
    - software-properties-common
    - apt-transport-https
    - apt-utils
    - apt
    - aptitude-common
    - aptitude
  notify: cleaning_packages_metadata
  tags:
    - docker

- name: Check if docker is installed
  package: name={{item}} state=present 
  check_mode: true
  ignore_errors: True
  with_items: 
    - docker-ce
  register: docker_package_check

- name: Setting docker repository
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
  args:
    warn: no
  notify: cleaning_packages_metadata
  when: docker_package_check is failed
  tags:
    - docker

- name: Setting docker repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && apt update && apt-cache policy docker-ce
  args:
    warn: no
  notify: cleaning_packages_metadata
  when: docker_package_check is failed
  tags:
    - docker

- name: Installing docker packages
  package: name={{item}} state=present
  with_items:
    - docker-ce-cli
    - docker-ce-rootless-extras
    - docker-ce
    - docker-compose-plugin
    - docker-compose
    - python3-docker
    - python3-dockerpty
    - python3-dockerpycreds
  notify: cleaning_packages_metadata
  when: docker_package_check is failed
  tags:
    - docker
